version: 2

sources:
  - name: MedicalData
    database: MedicalData
    schema: main
    tables:
      - name: raw_encounters_data
      - name: raw_patients_data
      - name: raw_conditions_data
      - name: raw_medications_data
      - name: raw_symptoms_data
